---
# yamllint disable rule:line-length rule:comments
version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
  - package-ecosystem: docker
    directory: /
    schedule:
      interval: weekly # bumps the Containerfile FROM tag (44 -> 45)
