---
# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"
silent: true

includes:
  yaml: ./tasks/yaml.yml
  shell: ./tasks/shell.yml
  build: ./tasks/build.yml
  vm: ./tasks/vm.yml

vars:
  IMAGE_NAME: os
  DEFAULT_TAG: latest

tasks:
  default:
    desc: List tasks
    cmd: task --list

  check:
    desc: Check for linting/formatting errors
    deps: ['yaml:check', 'shell:check']

  build:
    desc: Build the OCI image locally
    cmd: task build:image

  format:
    desc: Fix linting/formatting
    aliases: [fmt]
    deps: ['yaml:format', 'shell:format']

  clean:
    desc: Remove built image and disk artifacts
    cmds:
      - podman rmi -f localhost/{{.IMAGE_NAME}}:{{.DEFAULT_TAG}} 2>/dev/null || true
      - sudo podman rmi -f localhost/{{.IMAGE_NAME}}:{{.DEFAULT_TAG}} 2>/dev/null || true
      - rm -rf output .task
