---
# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"

tasks:
  iso:
    desc: Boot the installer ISO in a VM (open http://localhost:8006)
    cmd: >-
      sudo podman run --rm -it --privileged --pull=newer --publish 127.0.0.1:8006:8006 --device=/dev/kvm --volume ./output/bootiso/install.iso:/boot.iso docker.io/qemux/qemu
